import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static TextDirection directionOf(Locale locale) =>
      locale.languageCode == 'ar' ? TextDirection.rtl : TextDirection.ltr;

  static const _localizedValues = {
    'en': {
      'app_title': 'Foodly',
      'login': 'Login',
      'signup': 'Create account',
      'guest_login': 'Continue as guest',
      'home': 'Home',
      'restaurants': 'Restaurants',
      'my_cart': 'My Cart',
      'chat': 'Chat',
      'notifications': 'Notifications',
      'reservations': 'Reservations',
      'offers': 'Offers',
      'categories': 'Categories',
      'popular_items': 'Popular Items',
      'search_food': 'Search for food...',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'primary_color': 'Primary Color',
      'language': 'Language',
      'comparison': 'Comparison',
      'catalog': 'Catalog',
      'ai_info': 'AI Info',
      'favorites': 'Favorites',
      'orders': 'Orders',
      'book_table': 'Book a table',
      'reservation_manage': 'Manage reservations',
      'reservation_upcoming': 'Upcoming',
      'reservation_history': 'History',
      'reservation_empty_title': 'No reservations yet',
      'reservation_empty_subtitle': 'Save a table to elevate your next foodie gathering.',
      'reservation_history_empty_title': 'No past reservations',
      'reservation_history_empty_subtitle': 'Completed dine-in visits will appear here.',
      'reservation_status_confirmed': 'Confirmed',
      'reservation_status_completed': 'Completed',
      'reservation_status_cancelled': 'Cancelled',
      'reservation_occasion_casual': 'Casual meetup',
      'reservation_occasion_celebration': 'Celebration',
      'reservation_occasion_business': 'Business lunch',
      'reservation_occasion_date': 'Date night',
      'reservation_guests': 'Guests',
      'reservation_select_restaurant': 'Select restaurant',
      'reservation_select_slot': 'Select a time slot',
      'reservation_select_occasion': 'Choose an occasion',
      'reservation_notes_label': 'Special requests',
      'reservation_notes_placeholder': 'Add a note for the team (optional)',
      'reservation_no_slots': 'No slots available right now. Try another time.',
      'reservation_confirm_cta': 'Confirm booking',
      'reservation_saved': 'Reservation confirmed!',
      'reservation_mark_completed': 'Mark as completed',
      'reservation_cancel': 'Cancel reservation',
      'reservation_rebook': 'Rebook',
      'reservation_sheet_title': 'Plan dine-in',
      'reservation_sheet_subtitle': 'Pick a restaurant, time, and occasion to keep your night organized.',
      'reservation_sheet_hint': 'Tip: arrive 10 minutes early for the best seating.',
      'reservation_status_updated': 'Reservation updated.',
      'reservation_home_title': 'Dine-in concierge',
      'reservation_home_subtitle': 'Reserve a table ahead of time and sync with your foodie plans.',
      'reservation_home_cta': 'Plan dine-in experience',
      'help_center': 'Help Center',
      'profile': 'Profile',
      'rewards': 'Rewards',
      'meal_planner': 'Meal planner',
      'gift_cards': 'Gift cards',
      'gift_cards_title': 'Send delicious surprises',
      'gift_cards_subtitle': 'Share instant foodie joy with themed cards, curated perks, and flexible delivery.',
      'gift_cards_filter_all': 'All occasions',
      'gift_cards_perks_label': 'Add a little extra magic',
      'gift_cards_clear_perks': 'Clear perks',
      'gift_cards_empty_title': 'No gift kits match yet',
      'gift_cards_empty_subtitle': 'Adjust the filters to find the perfect foodie surprise.',
      'gift_cards_end_message': 'That is all for now. Fresh gifting ideas are on the way!',
      'currency_symbol_prefix': '\u0024',
      'community': 'Community',
      'community_intro': 'Join live cook-alongs, masterclasses, and foodie meetups curated for you.',
      'community_empty': 'Community stories are warming up. Check back shortly!',
      'community_refresh_cta': 'Pull to refresh and fetch the newest happenings.',
      'story_highlights': 'Story highlights',
      'live_now': 'Live now',
      'virtual_event': 'Virtual',
      'in_person_event': 'In-person',
      'hosted_by': 'Hosted by',
      'reserve_spot': 'Reserve spot',
      'spots_remaining': '%d spots left',
      'community_watch_now': 'Watch now',
      'community_minutes_short': 'min',
      'community_event_title_1': 'Spice Market Masterclass',
      'community_event_desc_1': 'Discover layering techniques with Chef Laila and cook along in real time.',
      'community_event_schedule_1': 'Tonight • 7:00 PM',
      'community_event_title_2': 'Garden-to-Table Workshop',
      'community_event_desc_2': 'Chef Omar shares seasonal plating ideas with fresh greens and grains.',
      'community_event_schedule_2': 'Thu • 5:30 PM',
      'community_event_title_3': 'Sunrise Brunch Club',
      'community_event_desc_3': 'Gather for early bites, mocktails, and playlists from Zoe’s team.',
      'community_event_schedule_3': 'Sat • 10:00 AM',
      'community_event_location_virtual': 'Streamed worldwide',
      'community_event_location_hq': 'Foodly HQ Studio, Downtown',
      'community_event_location_market': 'Bay Street Artisan Market',
      'community_host_laila': 'Chef Laila',
      'community_host_omar': 'Chef Omar',
      'community_host_zoe': 'Chef Zoe',
      'gift_occasion_thankyou': 'Thank you',
      'gift_occasion_birthday': 'Birthday',
      'gift_occasion_date': 'Date night',
      'gift_occasion_team': 'Team wins',
      'gift_occasion_congrats': 'Congrats',
      'gift_occasion_longdistance': 'Long distance',
      'gift_delivery_instant': 'Instant delivery',
      'gift_delivery_schedule': 'Scheduled send',
      'gift_delivery_bulk': 'Bulk delivery',
      'gift_bonus_loyalty': 'Bonus loyalty points',
      'gift_bonus_handwritten': 'Handwritten note enclosed',
      'gift_bonus_dual_course': 'Two-course upgrade',
      'gift_bonus_group_discount': 'Group dining bonus',
      'gift_bonus_breakfast': 'Brunch starter treats',
      'gift_bonus_timezone': 'Time-zone smart send',
      'gift_perk_free_delivery': 'Free delivery',
      'gift_perk_bonus_points': 'Extra points',
      'gift_perk_personal_note': 'Personal note',
      'gift_perk_scheduled_send': 'Schedule ahead',
      'gift_perk_premium_support': 'Concierge support',
      'gift_perk_bulk_upload': 'Bulk upload recipients',
      'gift_card_title_weekend': 'Weekend tasting duo',
      'gift_card_subtitle_weekend': 'Surprise a foodie friend with a weekend tasting flight.',
      'gift_card_title_brunch': 'Skyline brunch escape',
      'gift_card_subtitle_brunch': 'Reserve brunch delights with sparkling sips and playlists.',
      'gift_card_title_date_night': 'Date night under the lights',
      'gift_card_subtitle_date_night': 'Candle-lit mains and dessert pairings ready to impress.',
      'gift_card_title_team': 'Team celebration feast',
      'gift_card_subtitle_team': 'Reward the crew with shared plates and celebratory desserts.',
      'gift_card_title_morning': 'Morning coffee moments',
      'gift_card_subtitle_morning': 'Fuel productivity with artisan coffee and pastry bundles.',
      'gift_card_title_global': 'Global foodie hello',
      'gift_card_subtitle_global': 'Send a curated tasting kit across time zones instantly.',
      'community_story_title_1': 'Charred chili oil secrets',
      'community_story_desc_1': 'Chef Laila demos her signature pour-over chili crunch for noodles and eggs.',
      'community_story_title_2': 'Trend alert: crispy rice buns',
      'community_story_desc_2': 'Omar builds a crave-worthy handheld using toasted sushi rice buns.',
      'community_story_title_3': 'Seasonal mocktails',
      'community_story_desc_3': 'Zoe mixes sparkling citrus coolers perfect for brunch spreads.',
      'community_story_tag_masterclass': 'Masterclass',
      'community_story_tag_trend': 'Trend',
      'community_story_tag_seasonal': 'Seasonal',
      'weekly_focus': 'Weekly highlights',
      'auto_pilot': 'Auto pilot delivery',
      'auto_pilot_subtitle': 'Automatically repeat this plan each week and adjust with your saved preferences.',
      'rotate_plan': 'Shuffle week',
      'empty_meal_plan': 'Meal plan is loading. Pull to refresh for a fresh lineup.',
      'daily_calories': '%d kcal for the day',
      'prep_day': 'Prep day',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'focus_protein': 'Protein boost',
      'focus_greens': 'Green goodness',
      'focus_chef': 'Chef special',
      'focus_comfort': 'Comfort classics',
      'focus_spice': 'Spice fiesta',
      'focus_weekend': 'Weekend treats',
      'focus_brunch': 'Brunch & chill',
      'tip_hydrate': 'Hydrate well today and enjoy a citrus refresh.',
      'tip_extra_greens': 'Pair meals with a light salad for extra greens.',
      'tip_fruits': 'Add seasonal fruits to boost antioxidants.',
      'tip_mindful': 'Take a mindful break and savor every bite.',
      'tip_spice': 'Spice levels are adjustable — customize as you wish.',
      'tip_invite': 'Invite friends and share the experience.',
      'tip_brunch': 'Slow mornings deserve extra flavor and calm.',
      'currency_symbol': r'$',
      'catalog_title': 'Catalog',
      'deliver_to': 'Deliver to',
      'sample_city': 'San Francisco',
      'offer_banner_title': 'Up to 35% OFF',
      'offer_banner_subtitle': 'Delicious meals ready in minutes.',
      'fast_food': 'Fast Food',
      'sea_food': 'Sea Food',
      'dessert': 'Dessert',
      'crispy': 'Crispy',
      'pull_to_refresh': 'Pull to refresh',
      'empty_state': 'Nothing here yet',
      'retry': 'Retry',
      'search': 'Search',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'phone': 'Phone',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot password?',
      'get_started': 'Get Started',
      'shop_now': 'Shop Now',
      'view_all': 'View all',
      'updates_for_you': 'Updates for you',
      'add_to_cart': 'Add to Cart',
      'add_to_comparison': 'Add to Comparison',
      'add_to_favorites': 'Add to Favorites',
      'checkout': 'Checkout',
      'total': 'Total',
      'apply': 'Apply',
      'use_now': 'Use Now',
      'ai_placeholder': 'AI will analyze this item later... stay tuned!',
      'load_more': 'Load more',
      'loading_more': 'Loading more...',
      'no_more_results': 'You have reached the end.',
      'mark_all_read': 'Mark all as read',
      'notifications_empty_title': 'You are all caught up',
      'notifications_empty_subtitle': 'Fresh updates will land here soon.',
      'notification_type_order': 'Order update',
      'notification_type_offer': 'Offer',
      'notification_type_event': 'Event',
      'notification_type_tip': 'Pro tip',
      'notification_time_just_now': 'Just now',
      'notification_time_5m': '5 min ago',
      'notification_time_15m': '15 min ago',
      'notification_time_1h': '1 hour ago',
      'notification_time_yesterday': 'Yesterday',
      'notification_title_order_ready': 'Your order is heading out',
      'notification_body_order_ready': 'Rider Lina just picked up Fusion Delight 4. Track progress now.',
      'notification_title_offer_weekend': 'Weekend flash offer',
      'notification_body_offer_weekend': 'Get 25% off crispy bundles before midnight tonight.',
      'notification_title_event_live': 'Live cook-along starts soon',
      'notification_body_event_live': 'Chef Laila goes live in 15 minutes with her chili oil masterclass.',
      'notification_title_meal_plan': 'Prep tomorrow\'s plan',
      'notification_body_meal_plan': 'Switch auto pilot on to get groceries lined up for your planner.',
      'notification_title_loyalty': 'New reward unlocked',
      'notification_body_loyalty': 'You just crossed 1.2k points. Redeem a free dessert on your next order.',
      'notification_mark_read': 'Mark as read',
      'notification_marked_read': 'Marked as read',
      'close': 'Close',
      'minutes_delivery': 'min delivery',
      'empty_orders_message': 'No orders yet. Start exploring delicious meals.',
      'current': 'Current',
      'history': 'History',
      'track': 'Track',
      'order_updates': 'Order Updates',
      'offers_promotions': 'Offers & Promotions',
      'empty_favorites_title': 'Empty favorites',
      'empty_favorites_subtitle': 'Tap the heart icon on dishes to save them here.',
      'search_empty_subtitle': 'Try another keyword or explore categories.',
      'chat_title': 'Chat',
      'chat_intro': 'Hi Lina! Need help finding your next meal?',
      'chat_hint': 'Type your message...',
      'chat_bot_reply': 'Our concierge will respond shortly. Meanwhile, explore today\'s offers!',
      'send': 'Send',
      'best_match': 'Best match',
      'lowest_price': 'Lowest price',
      'highest_rating': 'Highest rating',
      'fastest_delivery': 'Fastest delivery',
      'view_more': 'View more',
      'view_rewards': 'View rewards',
      'manage_address': 'Manage Address',
      'payment_methods': 'Payment methods',
      'favorite_restaurants': 'Favorite restaurants',
      'logout': 'Logout',
      'logout_message': 'Logged out locally. Connect an account later to sync.',
      'lifetime_spend': 'Lifetime spend',
      'default': 'Default',
      'set_default': 'Set as default',
      'address_default_updated': '%s is now the default address.',
      'add_address': 'Add address',
      'address_added': 'New address saved to your profile.',
      'ending_in': 'Ending in',
      'expiry': 'Expiry',
      'primary_payment': 'Primary payment',
      'payment_primary_updated': '%s set as primary payment.',
      'make_default': 'Make default',
      'add_payment_method': 'Add payment method',
      'payment_added': 'Payment method added.',
      'claim_reward': 'Claim reward',
      'claim': 'Claim',
      'claimed': 'Claimed',
      'available_rewards': 'Available rewards',
      'progress_to_next': 'Progress to next tier',
      'milestone_ready': 'You are ready to unlock the next perk!',
      'points_remaining': '%d points until your next tier.',
      'boost_progress': 'Boost progress',
      'boost_ready': 'Progress boosted!',
      'milestone_claimed': 'Milestone claimed. Enjoy your new tier!',
      'reward_unlocked': 'Reward marked as unlocked.',
      'reward_saved': 'Reward saved for later.',
      'points': 'Points'
    },
    'ar': {
      'app_title': 'فودلي',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'guest_login': 'الدخول كضيف',
      'home': 'الرئيسية',
      'restaurants': 'المطاعم',
      'my_cart': 'سلة المشتريات',
      'chat': 'الدردشة',
      'notifications': 'الإشعارات',
      'reservations': 'الحجوزات',
      'offers': 'العروض',
      'categories': 'الفئات',
      'popular_items': 'الأطباق الشائعة',
      'search_food': 'ابحث عن طعام...',
      'settings': 'الإعدادات',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الرئيسي',
      'language': 'اللغة',
      'comparison': 'المقارنة',
      'catalog': 'الكتالوج',
      'ai_info': 'معلومات بالذكاء الاصطناعي',
      'favorites': 'المفضلة',
      'orders': 'الطلبات',
      'book_table': 'احجز طاولة',
      'reservation_manage': 'إدارة الحجوزات',
      'reservation_upcoming': 'القادمة',
      'reservation_history': 'السجل',
      'reservation_empty_title': 'لا توجد حجوزات بعد',
      'reservation_empty_subtitle': 'احجز طاولة مبكرًا لتستمتع بتجربة طعام مثالية.',
      'reservation_history_empty_title': 'لا يوجد سجل للحجوزات',
      'reservation_history_empty_subtitle': 'ستظهر زياراتك المكتملة هنا.',
      'reservation_status_confirmed': 'مؤكد',
      'reservation_status_completed': 'مكتمل',
      'reservation_status_cancelled': 'ملغي',
      'reservation_occasion_casual': 'لقاء ودي',
      'reservation_occasion_celebration': 'احتفال',
      'reservation_occasion_business': 'غداء عمل',
      'reservation_occasion_date': 'موعد رومانسي',
      'reservation_guests': 'ضيوف',
      'reservation_select_restaurant': 'اختر المطعم',
      'reservation_select_slot': 'اختر وقت الزيارة',
      'reservation_select_occasion': 'اختر المناسبة',
      'reservation_notes_label': 'ملاحظات خاصة',
      'reservation_notes_placeholder': 'أضف ملاحظة للفريق (اختياري)',
      'reservation_no_slots': 'لا توجد أوقات متاحة الآن، جرّب وقتًا آخر.',
      'reservation_confirm_cta': 'تأكيد الحجز',
      'reservation_saved': 'تم تأكيد الحجز!',
      'reservation_mark_completed': 'تعيين كمكتمل',
      'reservation_cancel': 'إلغاء الحجز',
      'reservation_rebook': 'إعادة الحجز',
      'reservation_sheet_title': 'تخطيط زيارة المطعم',
      'reservation_sheet_subtitle': 'اختر المطعم والوقت والمناسبة لتنظيم سهرتك.',
      'reservation_sheet_hint': 'نصيحة: الوصول قبل 10 دقائق يمنحك أفضل المقاعد.',
      'reservation_status_updated': 'تم تحديث الحجز.',
      'reservation_home_title': 'خدمة الحجز المسبق',
      'reservation_home_subtitle': 'احجز طاولتك مسبقًا ونسّق خططك الذوقية بسهولة.',
      'reservation_home_cta': 'خطط لتجربة تناول العشاء',
      'help_center': 'مركز المساعدة',
      'profile': 'الملف الشخصي',
      'rewards': 'المكافآت',
      'meal_planner': 'مخطط الوجبات',
      'gift_cards': 'بطاقات الهدايا',
      'gift_cards_title': 'أرسل مفاجآت شهية',
      'gift_cards_subtitle': 'شارك أجواء الطعام الفاخرة ببطاقات مخصصة ومزايا منسقة وخيارات تسليم مرنة.',
      'gift_cards_filter_all': 'كل المناسبات',
      'gift_cards_perks_label': 'أضف لمسة ساحرة',
      'gift_cards_clear_perks': 'مسح المزايا',
      'gift_cards_empty_title': 'لا توجد باقات مناسبة بعد',
      'gift_cards_empty_subtitle': 'عدّل عوامل التصفية للعثور على هدية الطعام المثالية.',
      'gift_cards_end_message': 'انتهت الاقتراحات الحالية. ترقب أفكار إهداء جديدة!',
      'currency_symbol_prefix': 'ر.س',
      'community': 'المجتمع',
      'community_intro': 'انضم إلى ورش الطهي المباشرة وحصص الخبراء ولقاءات عشاق الطعام المصممة لك.',
      'community_empty': 'يتم تجهيز القصص المجتمعية. عد لاحقًا!',
      'community_refresh_cta': 'اسحب للتحديث للحصول على آخر الفعاليات.',
      'story_highlights': 'أبرز القصص',
      'live_now': 'مباشر الآن',
      'virtual_event': 'افتراضي',
      'in_person_event': 'حضوري',
      'hosted_by': 'يقدمه',
      'reserve_spot': 'احجز مقعدك',
      'spots_remaining': 'متبقي %d مقاعد',
      'community_watch_now': 'شاهد الآن',
      'community_minutes_short': 'د',
      'community_event_title_1': 'ورشة التوابل الحارة',
      'community_event_desc_1': 'اكتشف تقنيات المزج مع الشيف ليلى واطبخ مباشرة.',
      'community_event_schedule_1': 'اليوم • 7:00 مساءً',
      'community_event_title_2': 'من الحديقة إلى المائدة',
      'community_event_desc_2': 'الشيف عمر يشارك أفكارًا موسمية للأطباق بالخضار الطازجة.',
      'community_event_schedule_2': 'الخميس • 5:30 مساءً',
      'community_event_title_3': 'نادي فطور الصباح',
      'community_event_desc_3': 'استمتع بوجبات صباحية ومشروبات منعشة مع فريق زوي.',
      'community_event_schedule_3': 'السبت • 10:00 صباحًا',
      'community_event_location_virtual': 'بث مباشر حول العالم',
      'community_event_location_hq': 'استوديو فودلي الرئيسي - وسط المدينة',
      'community_event_location_market': 'سوق باي ستريت للحرفيين',
      'community_host_laila': 'الشيف ليلى',
      'community_host_omar': 'الشيف عمر',
      'community_host_zoe': 'الشيف زوي',
      'gift_occasion_thankyou': 'شكراً لك',
      'gift_occasion_birthday': 'عيد ميلاد',
      'gift_occasion_date': 'موعد عشاء',
      'gift_occasion_team': 'نجاح الفريق',
      'gift_occasion_congrats': 'تهاني',
      'gift_occasion_longdistance': 'مسافات بعيدة',
      'gift_delivery_instant': 'تسليم فوري',
      'gift_delivery_schedule': 'إرسال مجدول',
      'gift_delivery_bulk': 'تسليم جماعي',
      'gift_bonus_loyalty': 'نقاط ولاء إضافية',
      'gift_bonus_handwritten': 'بطاقة تهنئة مكتوبة يدوياً',
      'gift_bonus_dual_course': 'ترقية لمسارين',
      'gift_bonus_group_discount': 'مكافأة للمجموعات',
      'gift_bonus_breakfast': 'مقبلات فطور',
      'gift_bonus_timezone': 'إرسال ذكي حسب التوقيت',
      'gift_perk_free_delivery': 'توصيل مجاني',
      'gift_perk_bonus_points': 'نقاط إضافية',
      'gift_perk_personal_note': 'رسالة شخصية',
      'gift_perk_scheduled_send': 'إرسال مسبق',
      'gift_perk_premium_support': 'دعم مميز',
      'gift_perk_bulk_upload': 'إرسال جماعي للمستلمين',
      'gift_card_title_weekend': 'تذوق عطلة نهاية الأسبوع',
      'gift_card_subtitle_weekend': 'فاجئ صديقك برحلة تذوق في عطلة نهاية الأسبوع.',
      'gift_card_title_brunch': 'برنش بإطلالة سماوية',
      'gift_card_subtitle_brunch': 'احجز برنشاً مع مشروبات منعشة وإيقاعات خاصة.',
      'gift_card_title_date_night': 'أمسية رومانسية متألقة',
      'gift_card_subtitle_date_night': 'أطباق على ضوء الشموع وحلويات جاهزة للإبهار.',
      'gift_card_title_team': 'وليمة للاحتفال بالفريق',
      'gift_card_subtitle_team': 'كافئ الفريق بأطباق مشاركة وحلويات احتفالية.',
      'gift_card_title_morning': 'لحظات القهوة الصباحية',
      'gift_card_subtitle_morning': 'ابدأ اليوم بقهوة فاخرة ومخبوزات طازجة.',
      'gift_card_title_global': 'تحية ذواقة حول العالم',
      'gift_card_subtitle_global': 'أرسل صندوق تذوق منسقاً لأحبائك أينما كانوا فوراً.',
      'community_story_title_1': 'أسرار زيت الفلفل المحمص',
      'community_story_desc_1': 'الشيف ليلى توضح صلصتها المقرمشة المفضلة للنودلز والبيض.',
      'community_story_title_2': 'صيحة كعكات الأرز المقرمشة',
      'community_story_desc_2': 'عمر يحضر شطيرة شهية باستخدام أرز السوشي المحمص.',
      'community_story_title_3': 'موكتيلات موسمية منعشة',
      'community_story_desc_3': 'زوي تمزج عصائر غازية بالحمضيات مثالية للفطور.',
      'community_story_tag_masterclass': 'ورشة احترافية',
      'community_story_tag_trend': 'صيحة',
      'community_story_tag_seasonal': 'موسمي',
      'weekly_focus': 'محاور الأسبوع',
      'auto_pilot': 'الوضع التلقائي',
      'auto_pilot_subtitle': 'قم بتكرار الخطة أسبوعياً مع ضبطها وفق تفضيلاتك المحفوظة.',
      'rotate_plan': 'تحديث الخطة',
      'empty_meal_plan': 'جاري تجهيز خطة الوجبات. اسحب للتحديث للحصول على قائمة جديدة.',
      'daily_calories': '%d سعرة حرارية لليوم',
      'prep_day': 'يوم التجهيز',
      'monday': 'الاثنين',
      'tuesday': 'الثلاثاء',
      'wednesday': 'الأربعاء',
      'thursday': 'الخميس',
      'friday': 'الجمعة',
      'saturday': 'السبت',
      'sunday': 'الأحد',
      'focus_protein': 'تعزيز البروتين',
      'focus_greens': 'خضار طازجة',
      'focus_chef': 'اختيار الشيف',
      'focus_comfort': 'أطباق مريحة',
      'focus_spice': 'مهرجان التوابل',
      'focus_weekend': 'مذاقات نهاية الأسبوع',
      'focus_brunch': 'برانش واسترخاء',
      'tip_hydrate': 'اشرب كمية كافية اليوم واستمتع بانتعاش الحمضيات.',
      'tip_extra_greens': 'أضف سلطة خفيفة للمزيد من الخضار.',
      'tip_fruits': 'أدرج الفواكه الموسمية لرفع مضادات الأكسدة.',
      'tip_mindful': 'خذ استراحة هادئة واستمتع بكل لقمة.',
      'tip_spice': 'يمكن تعديل مستوى التوابل — خصص الوجبة كما تحب.',
      'tip_invite': 'ادعُ الأصدقاء وشارك التجربة.',
      'tip_brunch': 'صباحات العطلة تستحق نكهة إضافية وهدوءاً.',
      'currency_symbol': r'$',
      'catalog_title': 'الكتالوج',
      'deliver_to': 'التوصيل إلى',
      'sample_city': 'سان فرانسيسكو',
      'offer_banner_title': 'خصم حتى ٣٥٪',
      'offer_banner_subtitle': 'وجبات شهية جاهزة خلال دقائق.',
      'fast_food': 'وجبات سريعة',
      'sea_food': 'مأكولات بحرية',
      'dessert': 'حلويات',
      'crispy': 'مقرمشات',
      'pull_to_refresh': 'اسحب للتحديث',
      'empty_state': 'لا يوجد محتوى بعد',
      'retry': 'إعادة المحاولة',
      'search': 'بحث',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'phone': 'الهاتف',
      'remember_me': 'تذكرني',
      'forgot_password': 'نسيت كلمة المرور؟',
      'get_started': 'ابدأ الآن',
      'shop_now': 'تسوق الآن',
      'view_all': 'عرض الكل',
      'updates_for_you': 'تحديثات لك',
      'add_to_cart': 'أضف إلى السلة',
      'add_to_comparison': 'أضف إلى المقارنة',
      'add_to_favorites': 'أضف إلى المفضلة',
      'checkout': 'الدفع',
      'total': 'الإجمالي',
      'apply': 'تطبيق',
      'use_now': 'استخدم الآن',
      'ai_placeholder': 'سيقوم الذكاء الاصطناعي بتحليل هذا الطبق لاحقًا... ترقب!',
      'load_more': 'المزيد',
      'loading_more': 'جاري تحميل المزيد...',
      'no_more_results': 'لقد وصلت للنهاية.',
      'mark_all_read': 'تحديد الكل كمقروء',
      'notifications_empty_title': 'أنت على اطلاع بكل شيء',
      'notifications_empty_subtitle': 'ستظهر التحديثات الجديدة هنا قريبًا.',
      'notification_type_order': 'تحديث طلب',
      'notification_type_offer': 'عرض',
      'notification_type_event': 'فعالية',
      'notification_type_tip': 'نصيحة',
      'notification_time_just_now': 'الآن',
      'notification_time_5m': 'منذ 5 دقائق',
      'notification_time_15m': 'منذ 15 دقيقة',
      'notification_time_1h': 'منذ ساعة',
      'notification_time_yesterday': 'أمس',
      'notification_title_order_ready': 'طلبك في الطريق',
      'notification_body_order_ready': 'السائق لينا استلمت وجبة فيوجن ديلايت 4. تتبع تقدمها الآن.',
      'notification_title_offer_weekend': 'عرض نهاية الأسبوع',
      'notification_body_offer_weekend': 'احصل على خصم 25% على باقات الكرسبي قبل منتصف الليل.',
      'notification_title_event_live': 'ورشة مباشرة تبدأ قريبًا',
      'notification_body_event_live': 'الشيف ليلى ستبث مباشرًا خلال 15 دقيقة بوصفة زيت الفلفل الخاصة بها.',
      'notification_title_meal_plan': 'جهز خطة الغد',
      'notification_body_meal_plan': 'فعّل الطيار الآلي لتحضير مشتريات مخطط الوجبات.',
      'notification_title_loyalty': 'مكافأة جديدة متاحة',
      'notification_body_loyalty': 'لقد تجاوزت ١٫٢ ألف نقطة. استبدل حلوى مجانية في طلبك القادم.',
      'notification_mark_read': 'تحديد كمقروء',
      'notification_marked_read': 'تم التحديد كمقروء',
      'close': 'إغلاق',
      'minutes_delivery': 'دقيقة للتوصيل',
      'empty_orders_message': 'لا توجد طلبات بعد. ابدأ باستكشاف الوجبات الشهية.',
      'current': 'الحالية',
      'history': 'السابق',
      'track': 'تتبع',
      'order_updates': 'تحديثات الطلب',
      'offers_promotions': 'العروض والتخفيضات',
      'empty_favorites_title': 'لا توجد عناصر مفضلة',
      'empty_favorites_subtitle': 'اضغط على أيقونة القلب لحفظ الأطباق هنا.',
      'search_empty_subtitle': 'جرّب كلمة أخرى أو استكشف الفئات.',
      'chat_title': 'الدردشة',
      'chat_intro': 'أهلًا لينا! هل تحتاجين مساعدة لاختيار وجبتك القادمة؟',
      'chat_hint': 'اكتبي رسالتك...',
      'chat_bot_reply': 'سيرد عليك المساعد قريبًا. في هذه الأثناء تصفحي عروض اليوم!',
      'send': 'إرسال',
      'best_match': 'الأفضل تطابقًا',
      'lowest_price': 'الأقل سعرًا',
      'highest_rating': 'الأعلى تقييمًا',
      'fastest_delivery': 'الأسرع توصيلًا',
      'view_more': 'عرض المزيد',
      'view_rewards': 'عرض المكافآت',
      'manage_address': 'إدارة العناوين',
      'payment_methods': 'طرق الدفع',
      'favorite_restaurants': 'المطاعم المفضلة',
      'logout': 'تسجيل الخروج',
      'logout_message': 'تم تسجيل الخروج محليًا. يمكنك ربط الحساب لاحقًا.',
      'lifetime_spend': 'إجمالي الإنفاق',
      'default': 'افتراضي',
      'set_default': 'تعيين كافتراضي',
      'address_default_updated': 'تم تعيين %s كعنوان افتراضي.',
      'add_address': 'إضافة عنوان',
      'address_added': 'تم حفظ العنوان الجديد في ملفك.',
      'ending_in': 'تنتهي بـ',
      'expiry': 'تاريخ الانتهاء',
      'primary_payment': 'طريقة الدفع الأساسية',
      'payment_primary_updated': 'تم تعيين %s كطريقة الدفع الأساسية.',
      'make_default': 'تعيين كافتراضي',
      'add_payment_method': 'إضافة طريقة دفع',
      'payment_added': 'تمت إضافة طريقة الدفع.',
      'claim_reward': 'استلم المكافأة',
      'claim': 'استلام',
      'claimed': 'مستلمة',
      'available_rewards': 'المكافآت المتاحة',
      'progress_to_next': 'التقدم نحو المستوى التالي',
      'milestone_ready': 'أنت جاهز لفتح الميزة التالية!',
      'points_remaining': 'متبقي %d نقطة للوصول للمستوى التالي.',
      'boost_progress': 'تعزيز التقدم',
      'boost_ready': 'تم تعزيز التقدم!',
      'milestone_claimed': 'تم استلام المكافأة. استمتع بالمستوى الجديد!',
      'reward_unlocked': 'تم وضع علامة على المكافأة كمستلمة.',
      'reward_saved': 'تم حفظ المكافأة لاحقًا.',
      'points': 'نقاط'
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.contains(Locale(locale.languageCode));

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
