import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static TextDirection directionOf(Locale locale) =>
      locale.languageCode == 'ar' ? TextDirection.rtl : TextDirection.ltr;

  static const _localizedValues = {
    'en': {
      'app_title': 'Foodly',
      'login': 'Login',
      'signup': 'Create account',
      'guest_login': 'Continue as guest',
      'home': 'Home',
      'restaurants': 'Restaurants',
      'my_cart': 'My Cart',
      'chat': 'Chat',
      'notifications': 'Notifications',
      'reservations': 'Reservations',
      'offers': 'Offers',
      'categories': 'Categories',
      'popular_items': 'Popular Items',
      'search_food': 'Search for food...',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'primary_color': 'Primary Color',
      'language': 'Language',
      'comparison': 'Comparison',
      'catalog': 'Catalog',
      'ai_info': 'AI Info',
      'favorites': 'Favorites',
      'orders': 'Orders',
      'book_table': 'Book a table',
      'reservation_manage': 'Manage reservations',
      'reservation_upcoming': 'Upcoming',
      'reservation_history': 'History',
      'reservation_empty_title': 'No reservations yet',
      'reservation_empty_subtitle': 'Save a table to elevate your next foodie gathering.',
      'reservation_history_empty_title': 'No past reservations',
      'reservation_history_empty_subtitle': 'Completed dine-in visits will appear here.',
      'reservation_status_confirmed': 'Confirmed',
      'reservation_status_completed': 'Completed',
      'reservation_status_cancelled': 'Cancelled',
      'reservation_occasion_casual': 'Casual meetup',
      'reservation_occasion_celebration': 'Celebration',
      'reservation_occasion_business': 'Business lunch',
      'reservation_occasion_date': 'Date night',
      'reservation_guests': 'Guests',
      'reservation_select_restaurant': 'Select restaurant',
      'reservation_select_slot': 'Select a time slot',
      'reservation_select_occasion': 'Choose an occasion',
      'reservation_notes_label': 'Special requests',
      'reservation_notes_placeholder': 'Add a note for the team (optional)',
      'reservation_no_slots': 'No slots available right now. Try another time.',
      'reservation_confirm_cta': 'Confirm booking',
      'reservation_saved': 'Reservation confirmed!',
      'reservation_mark_completed': 'Mark as completed',
      'reservation_cancel': 'Cancel reservation',
      'reservation_rebook': 'Rebook',
      'reservation_sheet_title': 'Plan dine-in',
      'reservation_sheet_subtitle': 'Pick a restaurant, time, and occasion to keep your night organized.',
      'reservation_sheet_hint': 'Tip: arrive 10 minutes early for the best seating.',
      'reservation_status_updated': 'Reservation updated.',
      'reservation_home_title': 'Dine-in concierge',
      'reservation_home_subtitle': 'Reserve a table ahead of time and sync with your foodie plans.',
      'reservation_home_cta': 'Plan dine-in experience',
      'help_center': 'Help Center',
      'profile': 'Profile',
      'rewards': 'Rewards',
      'meal_planner': 'Meal planner',
      'gift_cards': 'Gift cards',
      'gift_cards_title': 'Send delicious surprises',
      'gift_cards_subtitle': 'Share instant foodie joy with themed cards, curated perks, and flexible delivery.',
      'gift_cards_filter_all': 'All occasions',
      'gift_cards_perks_label': 'Add a little extra magic',
      'gift_cards_clear_perks': 'Clear perks',
      'gift_cards_empty_title': 'No gift kits match yet',
      'gift_cards_empty_subtitle': 'Adjust the filters to find the perfect foodie surprise.',
      'gift_cards_end_message': 'That is all for now. Fresh gifting ideas are on the way!',
      'catering': 'Catering',
      'catering_title': 'Host-ready catering journeys',
      'catering_subtitle': 'Plan immersive spreads with curated menus, styling, and concierge support.',
      'catering_filter_all_occasions': 'All occasions',
      'catering_filter_all_cuisines': 'All cuisines',
      'catering_filter_all_styles': 'All service styles',
      'catering_headcount_label': 'Guest range',
      'catering_service_label': 'Service style',
      'catering_clear_filters': 'Reset filters',
      'catering_empty_title': 'No catering menus match yet',
      'catering_empty_subtitle': 'Adjust the filters to reveal hosting-ready spreads.',
      'catering_end_message': 'More chef-curated spreads are baking.',
      'catering_price_from': 'From \$%s per guest',
      'catering_lead_time': 'Lead time • %d days',
      'catering_rating_label': '%s ★ rating',
      'catering_guest_range': 'Ideal for %s guests',
      'catering_view_details': 'View details',
      'catering_modal_title': 'Catering details',
      'catering_modal_highlights': 'Included highlights',
      'catering_modal_cuisines': 'Featured cuisines',
      'catering_modal_cta': 'Plan this spread',
      'catering_modal_secondary': 'Share menu',
      'catering_modal_note': 'Our concierge will confirm your final guest count after submission.',
      'catering_occasion_brunch': 'Creative brunch',
      'catering_occasion_corporate': 'Executive summit',
      'catering_occasion_product': 'Product launch',
      'catering_occasion_family': 'Family celebration',
      'catering_occasion_wellness': 'Wellness retreat',
      'catering_cuisine_mediterranean': 'Mediterranean',
      'catering_cuisine_modern': 'Modern global',
      'catering_cuisine_asian': 'Innovative Asian',
      'catering_cuisine_middle_eastern': 'Middle Eastern',
      'catering_cuisine_latino': 'Vibrant Latino',
      'catering_service_buffet': 'Interactive buffet',
      'catering_service_plated': 'Plated dining',
      'catering_service_family_style': 'Family-style',
      'catering_service_live_station': 'Live stations',
      'catering_headcount_small': '12-30 guests',
      'catering_headcount_medium': '30-75 guests',
      'catering_headcount_large': '75-150 guests',
      'catering_highlight_live_station': 'Live chef stations',
      'catering_highlight_styling': 'Signature tablescape styling',
      'catering_highlight_allergens': 'Allergen-friendly swaps',
      'catering_highlight_staffing': 'Full-service staffing',
      'catering_highlight_sommelier': 'Sommelier beverage pairings',
      'catering_highlight_tastings': 'Complimentary tasting',
      'catering_highlight_branding': 'Brandable signage moments',
      'catering_highlight_plant_forward': 'Plant-forward abundance',
      'catering_highlight_mindful_pairings': 'Mindful beverage pairings',
      'catering_package_title_brunch': 'Sunrise Feast Atelier',
      'catering_package_subtitle_brunch': 'Seasonal pastries, graze boards, and sparkling sips for creative mornings.',
      'catering_package_title_executive': 'Executive Board Indulgence',
      'catering_package_subtitle_executive': 'Multi-course plated experience with full staffing and sommelier pairings.',
      'catering_package_title_launch': 'Launchpad Showcase Spread',
      'catering_package_subtitle_launch': 'Live chef stations, branded moments, and wow-worthy tastings.',
      'catering_package_title_family': 'Family Gathering Abundance',
      'catering_package_subtitle_family': 'Shared platters with Levantine warmth and vibrant Mediterranean sides.',
      'catering_package_title_reset': 'Wellness Reset Banquet',
      'catering_package_subtitle_reset': 'Hydrating, nutrient-rich plates with mindful beverage pairings.',
      'masterclasses': 'Masterclasses',
      'masterclasses_title': 'Sharpen your craft with chef-led sessions',
      'masterclasses_subtitle':
          'Join immersive kitchens featuring live guidance, tasting menus, and pro techniques.',
      'masterclasses_filter_all_levels': 'All levels',
      'masterclasses_filter_all_cuisines': 'All cuisines',
      'masterclasses_filter_all_formats': 'All formats',
      'masterclasses_filter_level_beginner': 'Beginner-friendly',
      'masterclasses_filter_level_intermediate': 'Intermediate',
      'masterclasses_filter_level_advanced': 'Advanced',
      'masterclasses_format_in_person': 'In-studio',
      'masterclasses_format_virtual': 'Virtual live',
      'masterclasses_format_hybrid': 'Hybrid',
      'masterclasses_cuisine_italian': 'Italian artistry',
      'masterclasses_cuisine_middle_eastern': 'Middle Eastern',
      'masterclasses_cuisine_asian': 'Asian street food',
      'masterclasses_cuisine_plant_forward': 'Plant-forward',
      'masterclasses_empty_title': 'No classes match yet',
      'masterclasses_empty_subtitle': 'Adjust the filters to uncover your next kitchen adventure.',
      'masterclasses_end_message': 'Fresh masterclass drops arrive every week.',
      'masterclasses_duration_label': '%d min session',
      'masterclasses_spots_label': '%d spots left',
      'masterclasses_level_label': 'Level • %s',
      'masterclasses_instructor_label': 'Instructor',
      'masterclasses_view_details': 'View class details',
      'masterclasses_modal_title': 'Class overview',
      'masterclasses_modal_overview': 'What you will explore',
      'masterclasses_modal_takeaways': 'Skills & takeaways',
      'masterclasses_modal_requirements': 'What to prepare',
      'masterclasses_modal_instructor': 'Meet the chef',
      'masterclasses_modal_cta': 'Reserve your spot',
      'masterclasses_modal_secondary': 'Share class',
      'masterclasses_home_title': 'Chef masterclasses',
      'masterclasses_home_subtitle': 'Follow guided sessions to elevate your kitchen craft.',
      'masterclasses_home_cta': 'Explore classes',
      'masterclasses_highlight_station': 'Interactive tasting',
      'masterclasses_highlight_tools': 'Pro tool walk-through',
      'masterclasses_highlight_pairing': 'Pairing insights',
      'masterclasses_highlight_family': 'Family-friendly menu',
      'masterclasses_highlight_seasonal': 'Seasonal ingredients',
      'masterclasses_highlight_plating': 'Plating lab',
      'masterclasses_takeaway_pasta': 'Master hand-cut pasta dough',
      'masterclasses_takeaway_ferment': 'Start cultured ferments at home',
      'masterclasses_takeaway_plating': 'Plate like a Michelin chef',
      'masterclasses_takeaway_spice': 'Build signature spice blends',
      'masterclasses_requirement_apron': 'Apron & chef knife recommended',
      'masterclasses_requirement_workspace': 'Clear workspace and stable connection',
      'masterclasses_requirement_pan': 'Heavy-bottom pan or dutch oven',
      'masterclasses_requirement_blender': 'High-speed blender or food processor',
      'masterclasses_instructor_sophia': 'Chef Sophia Marelli',
      'masterclasses_instructor_story_sophia':
          'Truffle atelier owner guiding pasta craft and sensory pairing rituals.',
      'masterclasses_instructor_malik': 'Chef Malik Rahman',
      'masterclasses_instructor_story_malik':
          'Doha-based spice curator blending street food flair with modern technique.',
      'masterclasses_instructor_amelia': 'Chef Amelia Duarte',
      'masterclasses_instructor_story_amelia':
          'Plant-forward chef celebrating seasonal produce with immersive storytelling.',
      'masterclasses_instructor_hassan': 'Chef Hassan Al-Nouri',
      'masterclasses_instructor_story_hassan':
          'Levantine pitmaster sharing heritage grilling and family-style feasts.',
      'masterclasses_schedule_evening': 'Thursday • 7:00 PM (live)',
      'masterclasses_schedule_weekend': 'Saturday • 4:00 PM (studio)',
      'masterclasses_schedule_brunch': 'Friday • 11:00 AM (hybrid)',
      'masterclasses_schedule_twilight': 'Tuesday • 6:30 PM (studio)',
      'masterclass_title_truffle': 'Truffle Ribbon Pasta Lab',
      'masterclass_subtitle_truffle': 'Knead, roll, and sauce hand-cut pasta with aromatic pairings.',
      'masterclass_title_spice': 'Spice Market Skillet Tour',
      'masterclass_subtitle_spice':
          'Layer spices, sauces, and wok-fire techniques for bold street eats.',
      'masterclass_title_harvest': 'Seasonal Harvest Table',
      'masterclass_subtitle_harvest': 'Compose plant-forward plates with texture, color, and stories.',
      'masterclass_title_family_grill': 'Family Grill Residency',
      'masterclass_subtitle_family_grill':
          'Master Levantine marinades, smoke control, and shared plating.',
      'chefs': 'Chef spotlights',
      'chefs_title': 'Collaborate with visionary chefs',
      'chefs_subtitle':
          'Discover storytellers shaping the dining scene with signature experiences.',
      'chefs_filter_all_cuisines': 'All cuisines',
      'chefs_filter_all_specialties': 'All specialties',
      'chefs_filter_all_experiences': 'All journeys',
      'chefs_experience_filter_all': 'All experience levels',
      'chefs_experience_filter_8': '8+ years',
      'chefs_experience_filter_12': '12+ years',
      'chefs_clear_filters': 'Reset filters',
      'chefs_empty_title': 'No chefs match yet',
      'chefs_empty_subtitle': 'Adjust the filters to reveal more culinary storytellers.',
      'chefs_end_message': 'More chef spotlights arriving soon.',
      'chefs_experience_years': '%d years mastering flavors',
      'chefs_rating_label': '%s ★ storyteller',
      'chefs_detail_title': 'Meet the chef',
      'chefs_detail_specialties': 'Signature focuses',
      'chefs_detail_story': 'Culinary story',
      'chefs_detail_cta': 'Request collaboration',
      'chefs_detail_secondary': 'Save profile',
      'chef_specialty_tasting': 'Immersive tasting menus',
      'chef_specialty_plating': 'Sculpted plating artistry',
      'chef_specialty_wellness': 'Mindful nourishment',
      'chef_specialty_patisserie': 'Avant-garde patisserie',
      'chef_specialty_fire': 'Wood-fired mastery',
      'chef_specialty_collaboration': 'Collaborative residencies',
      'chef_highlight_story_dinners': 'Story-driven supper clubs',
      'chef_highlight_zero_waste': 'Zero-waste mise en place',
      'chef_highlight_award_winning': 'Award-winning accolades',
      'chef_highlight_globetrotting': 'Globetrotting inspiration',
      'chef_highlight_botanical': 'Botanical beverage pairings',
      'chef_highlight_concierge': 'Concierge production support',
      'chef_highlight_patisserie': 'Showstopping dessert atelier',
      'chef_name_amelia': 'Chef Amelia Torres',
      'chef_title_amelia': 'Botanical tasting architect',
      'chef_story_amelia':
          'From Madrid pop-ups to Dubai rooftops, Chef Amelia composes seasonal tasting journeys that weave edible florals, sensory storytelling, and zero-waste techniques into unforgettable nights.',
      'chef_name_kareem': 'Chef Kareem Al Najjar',
      'chef_title_kareem': 'Fire & spice visionary',
      'chef_story_kareem':
          'Raised in Amman and trained across Beirut and Istanbul, Chef Kareem brings Levantine fire cooking, aromatic spice rituals, and immersive communal tables to modern gatherings.',
      'chef_name_sofia': 'Chef Sofia Laurent',
      'chef_title_sofia': 'Modern patisserie auteur',
      'chef_story_sofia':
          'Paris-born Chef Sofia crafts sculptural patisserie, interactive dessert galleries, and multisensory finales that leave guests delighted long after the last bite.',
      'chef_name_tariq': 'Chef Tariq Mansour',
      'chef_title_tariq': 'Wellness cuisine curator',
      'chef_story_tariq':
          'Chef Tariq blends clinical nutrition insights with soulful Middle Eastern heritage to deliver restorative, plant-forward banquets and workplace nourishment labs.',
      'subscriptions': 'Subscriptions',
      'subscriptions_title': 'Chef-led plans tailored to your week',
      'subscriptions_subtitle': 'Lock in rotating menus, priority delivery, and guided prep support.',
      'subscriptions_filter_all': 'All journeys',
      'subscriptions_duration_weeks': '%d-week rhythm',
      'subscriptions_price_per_week': '%s / week',
      'subscriptions_refresh_hint': 'Pull to refresh and fetch the latest chef-curated plans.',
      'subscriptions_clear_filters': 'Reset filters',
      'subscriptions_perks_title': 'Included perks',
      'subscriptions_empty_title': 'No plans match yet',
      'subscriptions_empty_subtitle': 'Tweak the filters to reveal more curated journeys.',
      'subscriptions_badge_new': 'New',
      'subscriptions_badge_best_value': 'Best value',
      'subscriptions_explore_cta': 'Explore plans',
      'subscriptions_sheet_title': 'Plan details',
      'subscriptions_sheet_cta': 'Add to my journey',
      'subscription_plan_title_express': 'Express Flex Plan',
      'subscription_plan_desc_express': 'Three dinners per week with rotating global flavors and easy swaps.',
      'subscription_plan_title_wellness': 'Wellness Reset',
      'subscription_plan_desc_wellness': 'Plant-forward menus crafted with macro-balanced portions and guidance.',
      'subscription_plan_title_family': 'Family Feast Club',
      'subscription_plan_desc_family': 'Hearty sharable meals that cover busy weeknights with zero prep stress.',
      'subscription_plan_title_corporate': 'Office Fuel Pass',
      'subscription_plan_desc_corporate': 'Keep teams energized with curated lunches and scheduled deliveries.',
      'subscription_tag_flex': 'Flexitarian',
      'subscription_tag_wellness': 'Wellness boost',
      'subscription_tag_family': 'Family feast',
      'subscription_tag_corporate': 'Corporate fuel',
      'subscriptions_perk_free_setup': 'Free onboarding call',
      'subscriptions_perk_weekly_consult': 'Weekly nutrition consult',
      'subscriptions_perk_family_portions': 'Family-sized portions',
      'subscriptions_perk_priority_support': 'Priority concierge support',
      'subscriptions_perk_surprise': 'Friday surprise dessert',
      'wellness': 'Wellness',
      'wellness_title': 'Nourish your energy',
      'wellness_subtitle': 'Pair mindful bites with recovery rituals tailored to your week.',
      'wellness_refresh_hint': 'Pull to refresh to rebalance your plan.',
      'wellness_focus_all': 'All focuses',
      'wellness_focus_energy': 'Energy boost',
      'wellness_focus_mindful': 'Mindful reset',
      'wellness_focus_recovery': 'Active recovery',
      'wellness_focus_immune': 'Immune support',
      'wellness_duration_days': '%d-day journey',
      'wellness_empty_title': 'No wellness paths match yet',
      'wellness_empty_subtitle': 'Adjust the focus filters to reveal curated rituals.',
      'wellness_benefits_title': 'Why it works',
      'wellness_metrics_title': 'Daily rhythm',
      'wellness_metric_hydration': '%d glasses of hydration',
      'wellness_metric_focus': '%d min of focus reset',
      'wellness_metric_sleep': '%d hrs of wind-down',
      'wellness_sheet_title': 'Daily ritual snapshot',
      'wellness_sheet_cta': 'Add to my routine',
      'wellness_home_title': 'Wellness studio',
      'wellness_home_subtitle': 'Pair nourishing menus with mindful micro-habits.',
      'wellness_home_cta': 'Open studio',
      'wellness_end_message': 'More wellness journeys are on the way.',
      'wellness_benefit_balanced_plate': 'Balanced plate guidance',
      'wellness_benefit_breathwork': 'Guided breathwork audio',
      'wellness_benefit_mobility': 'Mobility flows included',
      'wellness_benefit_sleep': 'Sleep wind-down cues',
      'wellness_benefit_energy': 'Energy-boosting recipes',
      'wellness_benefit_immunity': 'Immunity-forward ingredients',
      'wellness_benefit_mood': 'Mood tracking journal',
      'wellness_benefit_desk': 'Desk stretch prompts',
      'wellness_program_title_energy': 'Radiant Energy Ritual',
      'wellness_program_subtitle_energy': 'Activate your mornings with bright flavors and breath resets.',
      'wellness_program_title_mindful': 'Mindful Evenings Flow',
      'wellness_program_subtitle_mindful': 'Ease into calm nights with herbal comforts and journaling.',
      'wellness_program_title_recovery': 'Active Recovery Restore',
      'wellness_program_subtitle_recovery': 'Fuel gentle movement days with protein-rich, anti-inflammatory picks.',
      'wellness_program_title_immune': 'Immune Guardian Boost',
      'wellness_program_subtitle_immune': 'Layer vibrant superfoods and hydration nudges all week.',
      'currency_symbol_prefix': '\u0024',
      'community': 'Community',
      'community_intro': 'Join live cook-alongs, masterclasses, and foodie meetups curated for you.',
      'community_empty': 'Community stories are warming up. Check back shortly!',
      'community_refresh_cta': 'Pull to refresh and fetch the newest happenings.',
      'story_highlights': 'Story highlights',
      'live_now': 'Live now',
      'virtual_event': 'Virtual',
      'in_person_event': 'In-person',
      'hosted_by': 'Hosted by',
      'reserve_spot': 'Reserve spot',
      'spots_remaining': '%d spots left',
      'community_watch_now': 'Watch now',
      'community_minutes_short': 'min',
      'community_event_title_1': 'Spice Market Masterclass',
      'community_event_desc_1': 'Discover layering techniques with Chef Laila and cook along in real time.',
      'community_event_schedule_1': 'Tonight • 7:00 PM',
      'community_event_title_2': 'Garden-to-Table Workshop',
      'community_event_desc_2': 'Chef Omar shares seasonal plating ideas with fresh greens and grains.',
      'community_event_schedule_2': 'Thu • 5:30 PM',
      'community_event_title_3': 'Sunrise Brunch Club',
      'community_event_desc_3': 'Gather for early bites, mocktails, and playlists from Zoe’s team.',
      'community_event_schedule_3': 'Sat • 10:00 AM',
      'community_event_location_virtual': 'Streamed worldwide',
      'community_event_location_hq': 'Foodly HQ Studio, Downtown',
      'community_event_location_market': 'Bay Street Artisan Market',
      'community_host_laila': 'Chef Laila',
      'community_host_omar': 'Chef Omar',
      'community_host_zoe': 'Chef Zoe',
      'gift_occasion_thankyou': 'Thank you',
      'gift_occasion_birthday': 'Birthday',
      'gift_occasion_date': 'Date night',
      'gift_occasion_team': 'Team wins',
      'gift_occasion_congrats': 'Congrats',
      'gift_occasion_longdistance': 'Long distance',
      'gift_delivery_instant': 'Instant delivery',
      'gift_delivery_schedule': 'Scheduled send',
      'gift_delivery_bulk': 'Bulk delivery',
      'gift_bonus_loyalty': 'Bonus loyalty points',
      'gift_bonus_handwritten': 'Handwritten note enclosed',
      'gift_bonus_dual_course': 'Two-course upgrade',
      'gift_bonus_group_discount': 'Group dining bonus',
      'gift_bonus_breakfast': 'Brunch starter treats',
      'gift_bonus_timezone': 'Time-zone smart send',
      'gift_perk_free_delivery': 'Free delivery',
      'gift_perk_bonus_points': 'Extra points',
      'gift_perk_personal_note': 'Personal note',
      'gift_perk_scheduled_send': 'Schedule ahead',
      'gift_perk_premium_support': 'Concierge support',
      'gift_perk_bulk_upload': 'Bulk upload recipients',
      'gift_card_title_weekend': 'Weekend tasting duo',
      'gift_card_subtitle_weekend': 'Surprise a foodie friend with a weekend tasting flight.',
      'gift_card_title_brunch': 'Skyline brunch escape',
      'gift_card_subtitle_brunch': 'Reserve brunch delights with sparkling sips and playlists.',
      'gift_card_title_date_night': 'Date night under the lights',
      'gift_card_subtitle_date_night': 'Candle-lit mains and dessert pairings ready to impress.',
      'gift_card_title_team': 'Team celebration feast',
      'gift_card_subtitle_team': 'Reward the crew with shared plates and celebratory desserts.',
      'gift_card_title_morning': 'Morning coffee moments',
      'gift_card_subtitle_morning': 'Fuel productivity with artisan coffee and pastry bundles.',
      'gift_card_title_global': 'Global foodie hello',
      'gift_card_subtitle_global': 'Send a curated tasting kit across time zones instantly.',
      'community_story_title_1': 'Charred chili oil secrets',
      'community_story_desc_1': 'Chef Laila demos her signature pour-over chili crunch for noodles and eggs.',
      'community_story_title_2': 'Trend alert: crispy rice buns',
      'community_story_desc_2': 'Omar builds a crave-worthy handheld using toasted sushi rice buns.',
      'community_story_title_3': 'Seasonal mocktails',
      'community_story_desc_3': 'Zoe mixes sparkling citrus coolers perfect for brunch spreads.',
      'community_story_tag_masterclass': 'Masterclass',
      'community_story_tag_trend': 'Trend',
      'community_story_tag_seasonal': 'Seasonal',
      'weekly_focus': 'Weekly highlights',
      'auto_pilot': 'Auto pilot delivery',
      'auto_pilot_subtitle': 'Automatically repeat this plan each week and adjust with your saved preferences.',
      'rotate_plan': 'Shuffle week',
      'empty_meal_plan': 'Meal plan is loading. Pull to refresh for a fresh lineup.',
      'daily_calories': '%d kcal for the day',
      'prep_day': 'Prep day',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'focus_protein': 'Protein boost',
      'focus_greens': 'Green goodness',
      'focus_chef': 'Chef special',
      'focus_comfort': 'Comfort classics',
      'focus_spice': 'Spice fiesta',
      'focus_weekend': 'Weekend treats',
      'focus_brunch': 'Brunch & chill',
      'tip_hydrate': 'Hydrate well today and enjoy a citrus refresh.',
      'tip_extra_greens': 'Pair meals with a light salad for extra greens.',
      'tip_fruits': 'Add seasonal fruits to boost antioxidants.',
      'tip_mindful': 'Take a mindful break and savor every bite.',
      'tip_spice': 'Spice levels are adjustable — customize as you wish.',
      'tip_invite': 'Invite friends and share the experience.',
      'tip_brunch': 'Slow mornings deserve extra flavor and calm.',
      'currency_symbol': r'$',
      'catalog_title': 'Catalog',
      'deliver_to': 'Deliver to',
      'sample_city': 'San Francisco',
      'offer_banner_title': 'Up to 35% OFF',
      'offer_banner_subtitle': 'Delicious meals ready in minutes.',
      'fast_food': 'Fast Food',
      'sea_food': 'Sea Food',
      'dessert': 'Dessert',
      'crispy': 'Crispy',
      'pull_to_refresh': 'Pull to refresh',
      'empty_state': 'Nothing here yet',
      'retry': 'Retry',
      'search': 'Search',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'phone': 'Phone',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot password?',
      'get_started': 'Get Started',
      'shop_now': 'Shop Now',
      'view_all': 'View all',
      'updates_for_you': 'Updates for you',
      'add_to_cart': 'Add to Cart',
      'add_to_comparison': 'Add to Comparison',
      'add_to_favorites': 'Add to Favorites',
      'checkout': 'Checkout',
      'total': 'Total',
      'apply': 'Apply',
      'use_now': 'Use Now',
      'ai_placeholder': 'AI will analyze this item later... stay tuned!',
      'load_more': 'Load more',
      'loading_more': 'Loading more...',
      'no_more_results': 'You have reached the end.',
      'mark_all_read': 'Mark all as read',
      'notifications_empty_title': 'You are all caught up',
      'notifications_empty_subtitle': 'Fresh updates will land here soon.',
      'notification_type_order': 'Order update',
      'notification_type_offer': 'Offer',
      'notification_type_event': 'Event',
      'notification_type_tip': 'Pro tip',
      'notification_time_just_now': 'Just now',
      'notification_time_5m': '5 min ago',
      'notification_time_15m': '15 min ago',
      'notification_time_1h': '1 hour ago',
      'notification_time_yesterday': 'Yesterday',
      'notification_title_order_ready': 'Your order is heading out',
      'notification_body_order_ready': 'Rider Lina just picked up Fusion Delight 4. Track progress now.',
      'notification_title_offer_weekend': 'Weekend flash offer',
      'notification_body_offer_weekend': 'Get 25% off crispy bundles before midnight tonight.',
      'notification_title_event_live': 'Live cook-along starts soon',
      'notification_body_event_live': 'Chef Laila goes live in 15 minutes with her chili oil masterclass.',
      'notification_title_meal_plan': 'Prep tomorrow\'s plan',
      'notification_body_meal_plan': 'Switch auto pilot on to get groceries lined up for your planner.',
      'notification_title_loyalty': 'New reward unlocked',
      'notification_body_loyalty': 'You just crossed 1.2k points. Redeem a free dessert on your next order.',
      'notification_mark_read': 'Mark as read',
      'notification_marked_read': 'Marked as read',
      'close': 'Close',
      'minutes_delivery': 'min delivery',
      'empty_orders_message': 'No orders yet. Start exploring delicious meals.',
      'current': 'Current',
      'history': 'History',
      'track': 'Track',
      'order_updates': 'Order Updates',
      'offers_promotions': 'Offers & Promotions',
      'empty_favorites_title': 'Empty favorites',
      'empty_favorites_subtitle': 'Tap the heart icon on dishes to save them here.',
      'search_empty_subtitle': 'Try another keyword or explore categories.',
      'chat_title': 'Chat',
      'chat_intro': 'Hi Lina! Need help finding your next meal?',
      'chat_hint': 'Type your message...',
      'chat_bot_reply': 'Our concierge will respond shortly. Meanwhile, explore today\'s offers!',
      'send': 'Send',
      'best_match': 'Best match',
      'lowest_price': 'Lowest price',
      'highest_rating': 'Highest rating',
      'fastest_delivery': 'Fastest delivery',
      'view_more': 'View more',
      'view_rewards': 'View rewards',
      'manage_address': 'Manage Address',
      'payment_methods': 'Payment methods',
      'favorite_restaurants': 'Favorite restaurants',
      'logout': 'Logout',
      'logout_message': 'Logged out locally. Connect an account later to sync.',
      'lifetime_spend': 'Lifetime spend',
      'default': 'Default',
      'set_default': 'Set as default',
      'address_default_updated': '%s is now the default address.',
      'add_address': 'Add address',
      'address_added': 'New address saved to your profile.',
      'ending_in': 'Ending in',
      'expiry': 'Expiry',
      'primary_payment': 'Primary payment',
      'payment_primary_updated': '%s set as primary payment.',
      'make_default': 'Make default',
      'add_payment_method': 'Add payment method',
      'payment_added': 'Payment method added.',
      'claim_reward': 'Claim reward',
      'claim': 'Claim',
      'claimed': 'Claimed',
      'available_rewards': 'Available rewards',
      'progress_to_next': 'Progress to next tier',
      'milestone_ready': 'You are ready to unlock the next perk!',
      'points_remaining': '%d points until your next tier.',
      'boost_progress': 'Boost progress',
      'boost_ready': 'Progress boosted!',
      'milestone_claimed': 'Milestone claimed. Enjoy your new tier!',
      'reward_unlocked': 'Reward marked as unlocked.',
      'reward_saved': 'Reward saved for later.',
      'points': 'Points'
    },
    'ar': {
      'app_title': 'فودلي',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'guest_login': 'الدخول كضيف',
      'home': 'الرئيسية',
      'restaurants': 'المطاعم',
      'my_cart': 'سلة المشتريات',
      'chat': 'الدردشة',
      'notifications': 'الإشعارات',
      'reservations': 'الحجوزات',
      'offers': 'العروض',
      'categories': 'الفئات',
      'popular_items': 'الأطباق الشائعة',
      'search_food': 'ابحث عن طعام...',
      'settings': 'الإعدادات',
      'dark_mode': 'الوضع الداكن',
      'primary_color': 'اللون الرئيسي',
      'language': 'اللغة',
      'comparison': 'المقارنة',
      'catalog': 'الكتالوج',
      'ai_info': 'معلومات بالذكاء الاصطناعي',
      'favorites': 'المفضلة',
      'orders': 'الطلبات',
      'book_table': 'احجز طاولة',
      'reservation_manage': 'إدارة الحجوزات',
      'reservation_upcoming': 'القادمة',
      'reservation_history': 'السجل',
      'reservation_empty_title': 'لا توجد حجوزات بعد',
      'reservation_empty_subtitle': 'احجز طاولة مبكرًا لتستمتع بتجربة طعام مثالية.',
      'reservation_history_empty_title': 'لا يوجد سجل للحجوزات',
      'reservation_history_empty_subtitle': 'ستظهر زياراتك المكتملة هنا.',
      'reservation_status_confirmed': 'مؤكد',
      'reservation_status_completed': 'مكتمل',
      'reservation_status_cancelled': 'ملغي',
      'reservation_occasion_casual': 'لقاء ودي',
      'reservation_occasion_celebration': 'احتفال',
      'reservation_occasion_business': 'غداء عمل',
      'reservation_occasion_date': 'موعد رومانسي',
      'reservation_guests': 'ضيوف',
      'reservation_select_restaurant': 'اختر المطعم',
      'reservation_select_slot': 'اختر وقت الزيارة',
      'reservation_select_occasion': 'اختر المناسبة',
      'reservation_notes_label': 'ملاحظات خاصة',
      'reservation_notes_placeholder': 'أضف ملاحظة للفريق (اختياري)',
      'reservation_no_slots': 'لا توجد أوقات متاحة الآن، جرّب وقتًا آخر.',
      'reservation_confirm_cta': 'تأكيد الحجز',
      'reservation_saved': 'تم تأكيد الحجز!',
      'reservation_mark_completed': 'تعيين كمكتمل',
      'reservation_cancel': 'إلغاء الحجز',
      'reservation_rebook': 'إعادة الحجز',
      'reservation_sheet_title': 'تخطيط زيارة المطعم',
      'reservation_sheet_subtitle': 'اختر المطعم والوقت والمناسبة لتنظيم سهرتك.',
      'reservation_sheet_hint': 'نصيحة: الوصول قبل 10 دقائق يمنحك أفضل المقاعد.',
      'reservation_status_updated': 'تم تحديث الحجز.',
      'reservation_home_title': 'خدمة الحجز المسبق',
      'reservation_home_subtitle': 'احجز طاولتك مسبقًا ونسّق خططك الذوقية بسهولة.',
      'reservation_home_cta': 'خطط لتجربة تناول العشاء',
      'help_center': 'مركز المساعدة',
      'profile': 'الملف الشخصي',
      'rewards': 'المكافآت',
      'meal_planner': 'مخطط الوجبات',
      'gift_cards': 'بطاقات الهدايا',
      'gift_cards_title': 'أرسل مفاجآت شهية',
      'gift_cards_subtitle': 'شارك أجواء الطعام الفاخرة ببطاقات مخصصة ومزايا منسقة وخيارات تسليم مرنة.',
      'gift_cards_filter_all': 'كل المناسبات',
      'gift_cards_perks_label': 'أضف لمسة ساحرة',
      'gift_cards_clear_perks': 'مسح المزايا',
      'gift_cards_empty_title': 'لا توجد باقات مناسبة بعد',
      'gift_cards_empty_subtitle': 'عدّل عوامل التصفية للعثور على هدية الطعام المثالية.',
      'gift_cards_end_message': 'انتهت الاقتراحات الحالية. ترقب أفكار إهداء جديدة!',
      'catering': 'الضيافة',
      'catering_title': 'رحلات ضيافة جاهزة للاستضافة',
      'catering_subtitle': 'خطط موائد غامرة بقوائم منسقة وتنسيقات أنيقة ودعم مخصص.',
      'catering_filter_all_occasions': 'كل المناسبات',
      'catering_filter_all_cuisines': 'كل المطابخ',
      'catering_filter_all_styles': 'كل أنماط التقديم',
      'catering_headcount_label': 'عدد الضيوف',
      'catering_service_label': 'نمط الخدمة',
      'catering_clear_filters': 'إعادة التعيين',
      'catering_empty_title': 'لا توجد قوائم مناسبة بعد',
      'catering_empty_subtitle': 'عدّل المرشحات لاكتشاف رحلات ضيافة جاهزة.',
      'catering_end_message': 'قوائم ضيافة جديدة في الطريق.',
      'catering_price_from': 'ابتداءً من %s\u0024 للشخص',
      'catering_lead_time': 'مدة التحضير \u2022 %d يومًا',
      'catering_rating_label': 'تقييم %s نجمة',
      'catering_guest_range': 'مثالي لـ %s ضيفًا',
      'catering_view_details': 'عرض التفاصيل',
      'catering_modal_title': 'تفاصيل الضيافة',
      'catering_modal_highlights': 'المزايا المضمنة',
      'catering_modal_cuisines': 'المطابخ المميزة',
      'catering_modal_cta': 'خطط لهذه القائمة',
      'catering_modal_secondary': 'مشاركة القائمة',
      'catering_modal_note': 'سيتواصل فريق الكونسييرج لتأكيد العدد النهائي بعد الإرسال.',
      'catering_occasion_brunch': 'برانش إبداعي',
      'catering_occasion_corporate': 'قمة تنفيذية',
      'catering_occasion_product': 'إطلاق منتج',
      'catering_occasion_family': 'احتفال عائلي',
      'catering_occasion_wellness': 'ملتقى عافية',
      'catering_cuisine_mediterranean': 'متوسطي',
      'catering_cuisine_modern': 'معاصر عالمي',
      'catering_cuisine_asian': 'آسيوي مبتكر',
      'catering_cuisine_middle_eastern': 'شرق أوسطي',
      'catering_cuisine_latino': 'لاتيني مشرق',
      'catering_service_buffet': 'بوفيه تفاعلي',
      'catering_service_plated': 'تقديم أطباق فردية',
      'catering_service_family_style': 'تقديم عائلي مشترك',
      'catering_service_live_station': 'محطات حية',
      'catering_headcount_small': 'من 12 إلى 30 ضيفًا',
      'catering_headcount_medium': 'من 30 إلى 75 ضيفًا',
      'catering_headcount_large': 'من 75 إلى 150 ضيفًا',
      'catering_highlight_live_station': 'محطات طهاة مباشرة',
      'catering_highlight_styling': 'تنسيق طاولات فاخر',
      'catering_highlight_allergens': 'خيارات بديلة للحساسيات',
      'catering_highlight_staffing': 'طاقم خدمة كامل',
      'catering_highlight_sommelier': 'تناغم مشروبات مع خبير',
      'catering_highlight_tastings': 'تذوق مسبق للقائمة',
      'catering_highlight_branding': 'عناصر تحمل هوية العلامة',
      'catering_highlight_plant_forward': 'قوائم نباتية غنية',
      'catering_highlight_mindful_pairings': 'تناغم مشروبات واعٍ',
      'catering_package_title_brunch': 'ورشة برانش الفجر',
      'catering_package_subtitle_brunch': 'موائد مليئة بالمعجنات الموسمية ولوحات التذوق والمشروبات الفوارة.',
      'catering_package_title_executive': 'ضيافة المجلس التنفيذي',
      'catering_package_subtitle_executive': 'قائمة متعددة الأطباق مع فريق خدمة متكامل وتناغم مشروبات راقٍ.',
      'catering_package_title_launch': 'انتشار إطلاق لامع',
      'catering_package_subtitle_launch': 'محطات طهاة مباشرة ولمسات علامة تجارية وتذوقات مبهرة.',
      'catering_package_title_family': 'لمة عائلية دافئة',
      'catering_package_subtitle_family': 'أطباق تشاركية بنكهات شامية ومتوسطية ولمسات نباتية.',
      'catering_package_title_reset': 'وليمة تجدد العافية',
      'catering_package_subtitle_reset': 'أطباق غنية بالعناصر الغذائية ومشروبات واعية تدعم إعادة الشحن.',
      'masterclasses': 'حصص الطهي',
      'masterclasses_title': 'طوّر مهاراتك مع جلسات يقودها الطهاة',
      'masterclasses_subtitle': 'انضم إلى مطابخ تفاعلية بتوجيه مباشر وتذوق وقصص الطهاة.',
      'masterclasses_filter_all_levels': 'كل المستويات',
      'masterclasses_filter_all_cuisines': 'كل المطابخ',
      'masterclasses_filter_all_formats': 'كل الأساليب',
      'masterclasses_filter_level_beginner': 'مناسب للمبتدئين',
      'masterclasses_filter_level_intermediate': 'متوسط',
      'masterclasses_filter_level_advanced': 'متقدم',
      'masterclasses_format_in_person': 'داخل الأستوديو',
      'masterclasses_format_virtual': 'بث مباشر',
      'masterclasses_format_hybrid': 'هجين',
      'masterclasses_cuisine_italian': 'مطبخ إيطالي',
      'masterclasses_cuisine_middle_eastern': 'مطبخ شرق أوسطي',
      'masterclasses_cuisine_asian': 'أطباق شارع آسيوية',
      'masterclasses_cuisine_plant_forward': 'نباتي مبتكر',
      'masterclasses_empty_title': 'لا توجد حصص مطابقة بعد',
      'masterclasses_empty_subtitle': 'عدّل عوامل التصفية للعثور على مغامرتك التالية في المطبخ.',
      'masterclasses_end_message': 'حصص جديدة تصل كل أسبوع.',
      'masterclasses_duration_label': 'جلسة %d دقيقة',
      'masterclasses_spots_label': '%d مقاعد متبقية',
      'masterclasses_level_label': 'المستوى • %s',
      'masterclasses_instructor_label': 'الشيف',
      'masterclasses_view_details': 'عرض تفاصيل الحصة',
      'masterclasses_modal_title': 'نظرة عامة على الحصة',
      'masterclasses_modal_overview': 'ماذا ستتعلم',
      'masterclasses_modal_takeaways': 'المهارات والمكتسبات',
      'masterclasses_modal_requirements': 'ما يجب تحضيره',
      'masterclasses_modal_instructor': 'تعرف على الشيف',
      'masterclasses_modal_cta': 'احجز مقعدك',
      'masterclasses_modal_secondary': 'مشاركة الحصة',
      'masterclasses_home_title': 'حصص الشيف المتقدمة',
      'masterclasses_home_subtitle': 'اتبع جلسات موجهة لرفع مستوى مهاراتك في المطبخ.',
      'masterclasses_home_cta': 'استكشف الحصص',
      'masterclasses_highlight_station': 'تذوق تفاعلي',
      'masterclasses_highlight_tools': 'جولة في الأدوات الاحترافية',
      'masterclasses_highlight_pairing': 'نصائح التناسق',
      'masterclasses_highlight_family': 'قائمة مناسبة للعائلة',
      'masterclasses_highlight_seasonal': 'مكونات موسمية',
      'masterclasses_highlight_plating': 'مختبر التقديم',
      'masterclasses_takeaway_pasta': 'اتقان عجينة الباستا الطازجة',
      'masterclasses_takeaway_ferment': 'بدء تخمير منزلي صحي',
      'masterclasses_takeaway_plating': 'التقديم بأسلوب ميشلان',
      'masterclasses_takeaway_spice': 'مزج خلطات التوابل المميزة',
      'masterclasses_requirement_apron': 'يفضل ارتداء مئزر وسكين شيف',
      'masterclasses_requirement_workspace': 'مساحة عمل مرتبة واتصال ثابت',
      'masterclasses_requirement_pan': 'قدر ثقيل القاع أو فرن هولندي',
      'masterclasses_requirement_blender': 'خلاط عالي السرعة أو محضرة طعام',
      'masterclasses_instructor_sophia': 'الشيف صوفيا ماريللي',
      'masterclasses_instructor_story_sophia': 'مالكة أتيليه الترافل التي تعلم عجينة الباستا وطقوس التذوق.',
      'masterclasses_instructor_malik': 'الشيف مالك رحمن',
      'masterclasses_instructor_story_malik': 'مبتكر توابل من الدوحة يمزج نكهات الشارع مع التقنيات الحديثة.',
      'masterclasses_instructor_amelia': 'الشيف أميليا دوارتي',
      'masterclasses_instructor_story_amelia': 'شيف نباتية تحتفي بالمواسم عبر قصص تفاعلية على المائدة.',
      'masterclasses_instructor_hassan': 'الشيف حسن النوري',
      'masterclasses_instructor_story_hassan': 'خبير شواء مشرقي يشارك أسرار التتبيل والولائم العائلية.',
      'masterclasses_schedule_evening': 'الخميس • 7:00 م (مباشر)',
      'masterclasses_schedule_weekend': 'السبت • 4:00 م (أستوديو)',
      'masterclasses_schedule_brunch': 'الجمعة • 11:00 ص (هجين)',
      'masterclasses_schedule_twilight': 'الثلاثاء • 6:30 م (أستوديو)',
      'masterclass_title_truffle': 'مختبر باستا الترافل',
      'masterclass_subtitle_truffle': 'اعجن ولف وقدم باستا طازجة مع تناغم عطري.',
      'masterclass_title_spice': 'جولة مقلاة سوق التوابل',
      'masterclass_subtitle_spice': 'تعلم تسلسل التوابل وتقنيات النار لأطباق شارع قوية.',
      'masterclass_title_harvest': 'مائدة الحصاد الموسمية',
      'masterclass_subtitle_harvest': 'شكّل أطباق نباتية بقوام وألوان وقصص.',
      'masterclass_title_family_grill': 'إقامة شواء عائلية',
      'masterclass_subtitle_family_grill': 'اتقن تتبيلات المطبخ الشامي والتحكم في الدخان والتقديم المشترك.',
      'chefs': 'مختارات الطهاة',
      'chefs_title': 'تعاون مع طهاة مبدعين',
      'chefs_subtitle': 'اكتشف رواة قصص يشكلون مشهد الطهي بتجارب مميزة.',
      'chefs_filter_all_cuisines': 'جميع المطابخ',
      'chefs_filter_all_specialties': 'جميع التخصصات',
      'chefs_filter_all_experiences': 'جميع الرحلات',
      'chefs_experience_filter_all': 'كل مستويات الخبرة',
      'chefs_experience_filter_8': '٨+ سنوات',
      'chefs_experience_filter_12': '١٢+ سنة',
      'chefs_clear_filters': 'إعادة التعيين',
      'chefs_empty_title': 'لا توجد ملفات للطهاة حتى الآن',
      'chefs_empty_subtitle': 'عدّل عوامل التصفية لإظهار مزيد من رواة القصص.',
      'chefs_end_message': 'قريبًا المزيد من تسليط الضوء على الطهاة.',
      'chefs_experience_years': '%d سنة من إتقان النكهات',
      'chefs_rating_label': '%s ★ راوي نكهات',
      'chefs_detail_title': 'تعرّف على الشيف',
      'chefs_detail_specialties': 'التركيزات المميزة',
      'chefs_detail_story': 'قصة الطهي',
      'chefs_detail_cta': 'طلب تعاون',
      'chefs_detail_secondary': 'حفظ الملف',
      'chef_specialty_tasting': 'قوائم تذوق غامرة',
      'chef_specialty_plating': 'فن تقديم منحوت',
      'chef_specialty_wellness': 'تغذية واعية',
      'chef_specialty_patisserie': 'حلويات مبتكرة',
      'chef_specialty_fire': 'إتقان النار والخشب',
      'chef_specialty_collaboration': 'إقامات تعاونية',
      'chef_highlight_story_dinners': 'عشاءات تحكي قصة',
      'chef_highlight_zero_waste': 'تحضير بلا هدر',
      'chef_highlight_award_winning': 'جوائز عالمية',
      'chef_highlight_globetrotting': 'إلهام من حول العالم',
      'chef_highlight_botanical': 'توليفات نباتية للمشروبات',
      'chef_highlight_concierge': 'دعم إنتاجي شامل',
      'chef_highlight_patisserie': 'مرسم حلويات مبهر',
      'chef_name_amelia': 'الشيف أميليا توريس',
      'chef_title_amelia': 'مهندسة تذوق نباتية',
      'chef_story_amelia':
          'من عروض مدريد إلى أسطح دبي، تنسج الشيف أميليا رحلات تذوق موسمية تمزج الزهور الصالحة للأكل وسرد القصص وتقنيات بلا هدر لليالٍ لا تُنسى.',
      'chef_name_kareem': 'الشيف كريم النجّار',
      'chef_title_kareem': 'رائد النار والتوابل',
      'chef_story_kareem':
          'نشأ في عمّان وتدرّب في بيروت وإسطنبول، يجلب الشيف كريم طهي النار الشامي وطقوس التوابل العطرية وموائد جماعية غامرة للتجمعات الحديثة.',
      'chef_name_sofia': 'الشيف صوفيا لوران',
      'chef_title_sofia': 'مبدعة حلويات عصرية',
      'chef_story_sofia':
          'الشيف صوفيا المولودة في باريس تصنع حلويات منحوتة ومعارض تحلية تفاعلية وخواتيم متعددة الحواس تبقي الضيوف مدهوشين بعد آخر لقمة.',
      'chef_name_tariq': 'الشيف طارق منصور',
      'chef_title_tariq': 'منسق مطبخ العافية',
      'chef_story_tariq':
          'يمزج الشيف طارق بين علم التغذية الإكلينيكي وجذوره الشرق أوسطية ليقدم ولائم نباتية تعيد الحيوية ومختبرات تغذية لأماكن العمل.',
      'subscriptions': 'الاشتراكات',
      'subscriptions_title': 'خطط أسبوعية يقودها الطهاة',
      'subscriptions_subtitle': 'ثبّت قوائم متجددة وتوصيل أولوية ودعم تحضير مخصص.',
      'subscriptions_filter_all': 'كل الرحلات',
      'subscriptions_duration_weeks': 'مدة %d أسابيع',
      'subscriptions_price_per_week': '%s / أسبوع',
      'subscriptions_refresh_hint': 'اسحب للتحديث للحصول على أحدث الخطط المنتقاة.',
      'subscriptions_clear_filters': 'إعادة تعيين التصفية',
      'subscriptions_perks_title': 'المزايا المشمولة',
      'subscriptions_empty_title': 'لا توجد خطط مطابقة بعد',
      'subscriptions_empty_subtitle': 'عدّل عوامل التصفية لاستكشاف المزيد من الرحلات المختارة.',
      'subscriptions_badge_new': 'جديد',
      'subscriptions_badge_best_value': 'أفضل قيمة',
      'subscriptions_explore_cta': 'استكشف الخطط',
      'subscriptions_sheet_title': 'تفاصيل الخطة',
      'subscriptions_sheet_cta': 'أضف إلى رحلتي',
      'subscription_plan_title_express': 'خطة فليكس السريعة',
      'subscription_plan_desc_express': 'ثلاث وجبات عشاء أسبوعياً بنكهات عالمية وتبديلات سهلة.',
      'subscription_plan_title_wellness': 'إعادة ضبط العافية',
      'subscription_plan_desc_wellness': 'قوائم نباتية متوازنة بالمغذيات مع إرشاد مستمر.',
      'subscription_plan_title_family': 'نادي الولائم العائلية',
      'subscription_plan_desc_family': 'وجبات مشبعة قابلة للمشاركة لتغطية ليالي الأسبوع المزدحمة دون عناء.',
      'subscription_plan_title_corporate': 'تصريح وقود المكتب',
      'subscription_plan_desc_corporate': 'حافظ على نشاط الفريق مع غداءات منسقة وتوصيل مجدول.',
      'subscription_tag_flex': 'مرن',
      'subscription_tag_wellness': 'دفعة عافية',
      'subscription_tag_family': 'عائلي',
      'subscription_tag_corporate': 'للشركات',
      'subscriptions_perk_free_setup': 'مكالمة إعداد مجانية',
      'subscriptions_perk_weekly_consult': 'استشارة تغذية أسبوعية',
      'subscriptions_perk_family_portions': 'حصص عائلية',
      'subscriptions_perk_priority_support': 'دعم أولوية',
      'subscriptions_perk_surprise': 'حلوى مفاجأة الجمعة',
      'wellness': 'العافية',
      'wellness_title': 'أنعش طاقتك',
      'wellness_subtitle': 'انسق وجبات واعية مع طقوس استشفاء تناسب أسبوعك.',
      'wellness_refresh_hint': 'اسحب للتحديث لإعادة موازنة خطتك.',
      'wellness_focus_all': 'جميع المحاور',
      'wellness_focus_energy': 'تعزيز الطاقة',
      'wellness_focus_mindful': 'هدوء ذهني',
      'wellness_focus_recovery': 'استشفاء نشط',
      'wellness_focus_immune': 'دعم المناعة',
      'wellness_duration_days': 'رحلة لمدة %d يوم',
      'wellness_empty_title': 'لا توجد مسارات عافية حالياً',
      'wellness_empty_subtitle': 'عدّل عوامل التصفية لإظهار طقوس مختارة.',
      'wellness_benefits_title': 'لماذا ينجح',
      'wellness_metrics_title': 'إيقاع يومي',
      'wellness_metric_hydration': '%d أكواب ماء',
      'wellness_metric_focus': '%d دقائق تركيز',
      'wellness_metric_sleep': '%d ساعات استرخاء',
      'wellness_sheet_title': 'لمحة عن الطقس اليومي',
      'wellness_sheet_cta': 'أضف إلى روتيني',
      'wellness_home_title': 'استوديو العافية',
      'wellness_home_subtitle': 'انسق قوائم مغذية مع عادات دقيقة.',
      'wellness_home_cta': 'افتح الاستوديو',
      'wellness_end_message': 'قصص عافية إضافية قريباً.',
      'wellness_benefit_balanced_plate': 'توجيه طبق متوازن',
      'wellness_benefit_breathwork': 'تمارين تنفس موجهة',
      'wellness_benefit_mobility': 'جلسات مرونة لطيفة',
      'wellness_benefit_sleep': 'إشارات لنوم هادئ',
      'wellness_benefit_energy': 'وصفات معززة للطاقة',
      'wellness_benefit_immunity': 'مكونات داعمة للمناعة',
      'wellness_benefit_mood': 'مفكرة تتبع المزاج',
      'wellness_benefit_desk': 'تنبيهات تمدد مكتبي',
      'wellness_program_title_energy': 'طقس طاقة متوهجة',
      'wellness_program_subtitle_energy': 'نشّط صباحك بنكهات مشرقة وتمارين تنفس.',
      'wellness_program_title_mindful': 'تدفق أمسيات هادئة',
      'wellness_program_subtitle_mindful': 'انتقل إلى ليالٍ ساكنة بأعشاب مهدئة ومذكرات.',
      'wellness_program_title_recovery': 'استشفاء نشط متجدد',
      'wellness_program_subtitle_recovery': 'زوّد أيام الحركة اللطيفة ببروتينات ومضادات التهاب.',
      'wellness_program_title_immune': 'تعزيز الحارس المناعي',
      'wellness_program_subtitle_immune': 'ادمج أطعمة فائقة وترطيب متواصل طوال الأسبوع.',
      'currency_symbol_prefix': 'ر.س',
      'community': 'المجتمع',
      'community_intro': 'انضم إلى ورش الطهي المباشرة وحصص الخبراء ولقاءات عشاق الطعام المصممة لك.',
      'community_empty': 'يتم تجهيز القصص المجتمعية. عد لاحقًا!',
      'community_refresh_cta': 'اسحب للتحديث للحصول على آخر الفعاليات.',
      'story_highlights': 'أبرز القصص',
      'live_now': 'مباشر الآن',
      'virtual_event': 'افتراضي',
      'in_person_event': 'حضوري',
      'hosted_by': 'يقدمه',
      'reserve_spot': 'احجز مقعدك',
      'spots_remaining': 'متبقي %d مقاعد',
      'community_watch_now': 'شاهد الآن',
      'community_minutes_short': 'د',
      'community_event_title_1': 'ورشة التوابل الحارة',
      'community_event_desc_1': 'اكتشف تقنيات المزج مع الشيف ليلى واطبخ مباشرة.',
      'community_event_schedule_1': 'اليوم • 7:00 مساءً',
      'community_event_title_2': 'من الحديقة إلى المائدة',
      'community_event_desc_2': 'الشيف عمر يشارك أفكارًا موسمية للأطباق بالخضار الطازجة.',
      'community_event_schedule_2': 'الخميس • 5:30 مساءً',
      'community_event_title_3': 'نادي فطور الصباح',
      'community_event_desc_3': 'استمتع بوجبات صباحية ومشروبات منعشة مع فريق زوي.',
      'community_event_schedule_3': 'السبت • 10:00 صباحًا',
      'community_event_location_virtual': 'بث مباشر حول العالم',
      'community_event_location_hq': 'استوديو فودلي الرئيسي - وسط المدينة',
      'community_event_location_market': 'سوق باي ستريت للحرفيين',
      'community_host_laila': 'الشيف ليلى',
      'community_host_omar': 'الشيف عمر',
      'community_host_zoe': 'الشيف زوي',
      'gift_occasion_thankyou': 'شكراً لك',
      'gift_occasion_birthday': 'عيد ميلاد',
      'gift_occasion_date': 'موعد عشاء',
      'gift_occasion_team': 'نجاح الفريق',
      'gift_occasion_congrats': 'تهاني',
      'gift_occasion_longdistance': 'مسافات بعيدة',
      'gift_delivery_instant': 'تسليم فوري',
      'gift_delivery_schedule': 'إرسال مجدول',
      'gift_delivery_bulk': 'تسليم جماعي',
      'gift_bonus_loyalty': 'نقاط ولاء إضافية',
      'gift_bonus_handwritten': 'بطاقة تهنئة مكتوبة يدوياً',
      'gift_bonus_dual_course': 'ترقية لمسارين',
      'gift_bonus_group_discount': 'مكافأة للمجموعات',
      'gift_bonus_breakfast': 'مقبلات فطور',
      'gift_bonus_timezone': 'إرسال ذكي حسب التوقيت',
      'gift_perk_free_delivery': 'توصيل مجاني',
      'gift_perk_bonus_points': 'نقاط إضافية',
      'gift_perk_personal_note': 'رسالة شخصية',
      'gift_perk_scheduled_send': 'إرسال مسبق',
      'gift_perk_premium_support': 'دعم مميز',
      'gift_perk_bulk_upload': 'إرسال جماعي للمستلمين',
      'gift_card_title_weekend': 'تذوق عطلة نهاية الأسبوع',
      'gift_card_subtitle_weekend': 'فاجئ صديقك برحلة تذوق في عطلة نهاية الأسبوع.',
      'gift_card_title_brunch': 'برنش بإطلالة سماوية',
      'gift_card_subtitle_brunch': 'احجز برنشاً مع مشروبات منعشة وإيقاعات خاصة.',
      'gift_card_title_date_night': 'أمسية رومانسية متألقة',
      'gift_card_subtitle_date_night': 'أطباق على ضوء الشموع وحلويات جاهزة للإبهار.',
      'gift_card_title_team': 'وليمة للاحتفال بالفريق',
      'gift_card_subtitle_team': 'كافئ الفريق بأطباق مشاركة وحلويات احتفالية.',
      'gift_card_title_morning': 'لحظات القهوة الصباحية',
      'gift_card_subtitle_morning': 'ابدأ اليوم بقهوة فاخرة ومخبوزات طازجة.',
      'gift_card_title_global': 'تحية ذواقة حول العالم',
      'gift_card_subtitle_global': 'أرسل صندوق تذوق منسقاً لأحبائك أينما كانوا فوراً.',
      'community_story_title_1': 'أسرار زيت الفلفل المحمص',
      'community_story_desc_1': 'الشيف ليلى توضح صلصتها المقرمشة المفضلة للنودلز والبيض.',
      'community_story_title_2': 'صيحة كعكات الأرز المقرمشة',
      'community_story_desc_2': 'عمر يحضر شطيرة شهية باستخدام أرز السوشي المحمص.',
      'community_story_title_3': 'موكتيلات موسمية منعشة',
      'community_story_desc_3': 'زوي تمزج عصائر غازية بالحمضيات مثالية للفطور.',
      'community_story_tag_masterclass': 'ورشة احترافية',
      'community_story_tag_trend': 'صيحة',
      'community_story_tag_seasonal': 'موسمي',
      'weekly_focus': 'محاور الأسبوع',
      'auto_pilot': 'الوضع التلقائي',
      'auto_pilot_subtitle': 'قم بتكرار الخطة أسبوعياً مع ضبطها وفق تفضيلاتك المحفوظة.',
      'rotate_plan': 'تحديث الخطة',
      'empty_meal_plan': 'جاري تجهيز خطة الوجبات. اسحب للتحديث للحصول على قائمة جديدة.',
      'daily_calories': '%d سعرة حرارية لليوم',
      'prep_day': 'يوم التجهيز',
      'monday': 'الاثنين',
      'tuesday': 'الثلاثاء',
      'wednesday': 'الأربعاء',
      'thursday': 'الخميس',
      'friday': 'الجمعة',
      'saturday': 'السبت',
      'sunday': 'الأحد',
      'focus_protein': 'تعزيز البروتين',
      'focus_greens': 'خضار طازجة',
      'focus_chef': 'اختيار الشيف',
      'focus_comfort': 'أطباق مريحة',
      'focus_spice': 'مهرجان التوابل',
      'focus_weekend': 'مذاقات نهاية الأسبوع',
      'focus_brunch': 'برانش واسترخاء',
      'tip_hydrate': 'اشرب كمية كافية اليوم واستمتع بانتعاش الحمضيات.',
      'tip_extra_greens': 'أضف سلطة خفيفة للمزيد من الخضار.',
      'tip_fruits': 'أدرج الفواكه الموسمية لرفع مضادات الأكسدة.',
      'tip_mindful': 'خذ استراحة هادئة واستمتع بكل لقمة.',
      'tip_spice': 'يمكن تعديل مستوى التوابل — خصص الوجبة كما تحب.',
      'tip_invite': 'ادعُ الأصدقاء وشارك التجربة.',
      'tip_brunch': 'صباحات العطلة تستحق نكهة إضافية وهدوءاً.',
      'currency_symbol': r'$',
      'catalog_title': 'الكتالوج',
      'deliver_to': 'التوصيل إلى',
      'sample_city': 'سان فرانسيسكو',
      'offer_banner_title': 'خصم حتى ٣٥٪',
      'offer_banner_subtitle': 'وجبات شهية جاهزة خلال دقائق.',
      'fast_food': 'وجبات سريعة',
      'sea_food': 'مأكولات بحرية',
      'dessert': 'حلويات',
      'crispy': 'مقرمشات',
      'pull_to_refresh': 'اسحب للتحديث',
      'empty_state': 'لا يوجد محتوى بعد',
      'retry': 'إعادة المحاولة',
      'search': 'بحث',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'phone': 'الهاتف',
      'remember_me': 'تذكرني',
      'forgot_password': 'نسيت كلمة المرور؟',
      'get_started': 'ابدأ الآن',
      'shop_now': 'تسوق الآن',
      'view_all': 'عرض الكل',
      'updates_for_you': 'تحديثات لك',
      'add_to_cart': 'أضف إلى السلة',
      'add_to_comparison': 'أضف إلى المقارنة',
      'add_to_favorites': 'أضف إلى المفضلة',
      'checkout': 'الدفع',
      'total': 'الإجمالي',
      'apply': 'تطبيق',
      'use_now': 'استخدم الآن',
      'ai_placeholder': 'سيقوم الذكاء الاصطناعي بتحليل هذا الطبق لاحقًا... ترقب!',
      'load_more': 'المزيد',
      'loading_more': 'جاري تحميل المزيد...',
      'no_more_results': 'لقد وصلت للنهاية.',
      'mark_all_read': 'تحديد الكل كمقروء',
      'notifications_empty_title': 'أنت على اطلاع بكل شيء',
      'notifications_empty_subtitle': 'ستظهر التحديثات الجديدة هنا قريبًا.',
      'notification_type_order': 'تحديث طلب',
      'notification_type_offer': 'عرض',
      'notification_type_event': 'فعالية',
      'notification_type_tip': 'نصيحة',
      'notification_time_just_now': 'الآن',
      'notification_time_5m': 'منذ 5 دقائق',
      'notification_time_15m': 'منذ 15 دقيقة',
      'notification_time_1h': 'منذ ساعة',
      'notification_time_yesterday': 'أمس',
      'notification_title_order_ready': 'طلبك في الطريق',
      'notification_body_order_ready': 'السائق لينا استلمت وجبة فيوجن ديلايت 4. تتبع تقدمها الآن.',
      'notification_title_offer_weekend': 'عرض نهاية الأسبوع',
      'notification_body_offer_weekend': 'احصل على خصم 25% على باقات الكرسبي قبل منتصف الليل.',
      'notification_title_event_live': 'ورشة مباشرة تبدأ قريبًا',
      'notification_body_event_live': 'الشيف ليلى ستبث مباشرًا خلال 15 دقيقة بوصفة زيت الفلفل الخاصة بها.',
      'notification_title_meal_plan': 'جهز خطة الغد',
      'notification_body_meal_plan': 'فعّل الطيار الآلي لتحضير مشتريات مخطط الوجبات.',
      'notification_title_loyalty': 'مكافأة جديدة متاحة',
      'notification_body_loyalty': 'لقد تجاوزت ١٫٢ ألف نقطة. استبدل حلوى مجانية في طلبك القادم.',
      'notification_mark_read': 'تحديد كمقروء',
      'notification_marked_read': 'تم التحديد كمقروء',
      'close': 'إغلاق',
      'minutes_delivery': 'دقيقة للتوصيل',
      'empty_orders_message': 'لا توجد طلبات بعد. ابدأ باستكشاف الوجبات الشهية.',
      'current': 'الحالية',
      'history': 'السابق',
      'track': 'تتبع',
      'order_updates': 'تحديثات الطلب',
      'offers_promotions': 'العروض والتخفيضات',
      'empty_favorites_title': 'لا توجد عناصر مفضلة',
      'empty_favorites_subtitle': 'اضغط على أيقونة القلب لحفظ الأطباق هنا.',
      'search_empty_subtitle': 'جرّب كلمة أخرى أو استكشف الفئات.',
      'chat_title': 'الدردشة',
      'chat_intro': 'أهلًا لينا! هل تحتاجين مساعدة لاختيار وجبتك القادمة؟',
      'chat_hint': 'اكتبي رسالتك...',
      'chat_bot_reply': 'سيرد عليك المساعد قريبًا. في هذه الأثناء تصفحي عروض اليوم!',
      'send': 'إرسال',
      'best_match': 'الأفضل تطابقًا',
      'lowest_price': 'الأقل سعرًا',
      'highest_rating': 'الأعلى تقييمًا',
      'fastest_delivery': 'الأسرع توصيلًا',
      'view_more': 'عرض المزيد',
      'view_rewards': 'عرض المكافآت',
      'manage_address': 'إدارة العناوين',
      'payment_methods': 'طرق الدفع',
      'favorite_restaurants': 'المطاعم المفضلة',
      'logout': 'تسجيل الخروج',
      'logout_message': 'تم تسجيل الخروج محليًا. يمكنك ربط الحساب لاحقًا.',
      'lifetime_spend': 'إجمالي الإنفاق',
      'default': 'افتراضي',
      'set_default': 'تعيين كافتراضي',
      'address_default_updated': 'تم تعيين %s كعنوان افتراضي.',
      'add_address': 'إضافة عنوان',
      'address_added': 'تم حفظ العنوان الجديد في ملفك.',
      'ending_in': 'تنتهي بـ',
      'expiry': 'تاريخ الانتهاء',
      'primary_payment': 'طريقة الدفع الأساسية',
      'payment_primary_updated': 'تم تعيين %s كطريقة الدفع الأساسية.',
      'make_default': 'تعيين كافتراضي',
      'add_payment_method': 'إضافة طريقة دفع',
      'payment_added': 'تمت إضافة طريقة الدفع.',
      'claim_reward': 'استلم المكافأة',
      'claim': 'استلام',
      'claimed': 'مستلمة',
      'available_rewards': 'المكافآت المتاحة',
      'progress_to_next': 'التقدم نحو المستوى التالي',
      'milestone_ready': 'أنت جاهز لفتح الميزة التالية!',
      'points_remaining': 'متبقي %d نقطة للوصول للمستوى التالي.',
      'boost_progress': 'تعزيز التقدم',
      'boost_ready': 'تم تعزيز التقدم!',
      'milestone_claimed': 'تم استلام المكافأة. استمتع بالمستوى الجديد!',
      'reward_unlocked': 'تم وضع علامة على المكافأة كمستلمة.',
      'reward_saved': 'تم حفظ المكافأة لاحقًا.',
      'points': 'نقاط'
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.contains(Locale(locale.languageCode));

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
